# hypersphere の場合: dataset_path, R, r, embed_dataは使わない

time_step: 1000
data_size: 50000
dim_d: 24 # ambient space dimension of the hypersphere
dim_z: 20 # latent space dimension of the hypersphere
is_train: True
batch_size: 1000
dataset_name: "embed_sphere"
dataset_path: "/workspace/data/fashion_mnist/z_mean_S20_cnn.pt"
R: 3
r: 1
denoise_model : "Unet"
show_other_inj_line: False

# embed_sphere の場合にのみ指定されるフィールド
embed_data: "fashion_mnist"  # 例えば、"type_a"や"type_b"など