# circle の場合: n:data_size, dim_d: ambient space, 実装は単位円にのみ対応

time_step: 1000
data_size: 50000
dim_d: 16 # ambient space dimension of the hypersphere
dim_z: 10 # latent space dimension of the hypersphere
is_train: True
batch_size: 1000
dataset_name: "s_0"
dataset_path: "/workspace/data/fashion_mnist/z_mean_S10_cnn.pt"
R: 3
r: 1
denoise_model : "Unet"
show_other_inj_line: False


# embed_sphere の場合にのみ指定されるフィールド
embed_data: "fashion_mnist"  # 例えば、"type_a"や"type_b"など

