time_step: 1000
data_size: 5000
dim_d: 24
dim_z: 7
is_train: True
batch_size: 1000
dataset_name: "circle_two_injectivity"
dataset_path: "/workspace/data/mnist/z_mean_S20.pt"
R: 3
r: 1
denoise_model : "Unet"