time_step: 1000
data_size: 50000
dim_d: 16 # ambient space dimension of the hypersphere
dim_z: 10 # latent space dimension of the hypersphere
is_train: True
batch_size: 1000
dataset_name: "embed_sphere"
dataset_path: "/workspace/data/mnist/z_mean_S10.pt"
R: 3
r: 1
denoise_model : "Unet"