# circle_two_injectivity の場合: n:data_size, dim_d: ambient space

time_step: 1000
data_size: 50000
dim_d: 16 # ambient space dimension of the hypersphere
dim_z: 10 # latent space dimension of the hypersphere
is_train: True
batch_size: 1000
dataset_name: "circle_two_injectivity"
dataset_path: "/workspace/data/fashion_mnist/z_mean_S10_cnn.pt"
R: 2
r: 1
denoise_model : "Unet"
show_other_inj_line: True

# embed_sphere の場合にのみ指定されるフィールド
embed_data: "fashion_mnist"  # 例えば、"type_a"や"type_b"など